#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : keychain
Version  : 2.8.5
Release  : 3
URL      : https://github.com/funtoo/keychain/archive/2.8.5.tar.gz
Source0  : https://github.com/funtoo/keychain/archive/2.8.5.tar.gz
Summary  : agent manager for OpenSSH, ssh.com, Sun SSH, and GnuPG
Group    : Development/Tools
License  : GPL-2.0
Requires: keychain-bin = %{version}-%{release}
Requires: keychain-license = %{version}-%{release}
Requires: keychain-man = %{version}-%{release}
Patch1: 0001-Add-install-target.patch

%description
Keychain is a manager for OpenSSH, ssh.com, Sun SSH and GnuPG agents.
It acts as a front-end to the agents, allowing you to easily have one
long-running agent process per system, rather than per login session.
This reduces the number of times you need to enter your passphrase
from once per new login session to once every time your local machine
is rebooted.

%package bin
Summary: bin components for the keychain package.
Group: Binaries
Requires: keychain-license = %{version}-%{release}

%description bin
bin components for the keychain package.


%package license
Summary: license components for the keychain package.
Group: Default

%description license
license components for the keychain package.


%package man
Summary: man components for the keychain package.
Group: Default

%description man
man components for the keychain package.


%prep
%setup -q -n keychain-2.8.5
cd %{_builddir}/keychain-2.8.5
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1604098440
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1604098440
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/keychain
cp %{_builddir}/keychain-2.8.5/COPYING.txt %{buildroot}/usr/share/package-licenses/keychain/cc501127ed2d0d41c4892d6e6ce6a9ea51c3d4bf
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/keychain

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/keychain/cc501127ed2d0d41c4892d6e6ce6a9ea51c3d4bf

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/keychain.1
